[package]
name = "sf-scrapbook-helper"
version = "0.2.0"
edition = "2021"


[dependencies]
ahash = "0.8.11"
async-compression = { version = "0.4.6", features = ["zlib"] }
chrono = "0.4.34"
fastrand = "2.0.1"
iced = { version = "0.12", features = ["tokio", "lazy"] }
iced_aw = { version = "0.8.0", default-features = false, features = [
    "number_input",
] }
image = { version = "0.24.9", default-features = false, features = ["png"] }
nohash-hasher = "0.2.0"
open = "5.1.1"
reqwest = { version = "0.11.24", features = ["gzip", "deflate", "brotli"] }
serde = "1.0.197"
serde_json = "1.0.114"
sf-api = { git = "https://github.com/the-marenga/sf-api", version = "0.1.2" }
titlecase = "2.2.1"
tokio = { version = "1.36.0", default-features = false, features = ["fs"] }
toml = "0.8.10"

[build-dependencies]
winres = "0.1.12"
