[package]
name = "sf-scrapbook-helper"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.34"
eframe = "0.26"
env_logger = "0.11.2"
fastrand = "2.0.1"
flate2 = "1.0.28"
log = "0.4.20"
nohash-hasher = "0.2.0"
once_cell = "1.19.0"
reqwest = { version = "0.11.24", features = ["gzip", "deflate", "brotli"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sf-api = "0.1.0"
tokio = { version = "1.36.0", features = ["net", "rt-multi-thread", "fs"] }
twox-hash = { version = "1.6.3", default-features = false }

[profile.release]
strip = true
lto = true