[package]
name = "sf-scrapbook-helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
eframe = "0.24.1"
fastrand = "2.0.1"
once_cell = "1.19.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sf-api = { git = "https://github.com/the-marenga/sf-api.git", version = "0.0.1" }
tokio = { version = "1.35.1", features = ["net", "rt-multi-thread"] }
twox-hash = { version = "1.6.3", default-features = false }

[profile.release]
strip = true
# lto = true